version: 2
jobs:
  setup: &exector
    working_directory: ~/work
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - restore_cache:
          name: Restore npm dependencies
          key: npm-{{ checksum "package-lock.json" }}-{{ .Environment.CACHE_VERSION_NPM }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          name: Cache npm dependencies
          key: npm-{{ checksum "package-lock.json" }}-{{ .Environment.CACHE_VERSION_NPM }}
          paths:
            - ~/work/node_modules
      - persist_to_workspace:
          root: .
          paths:
            - ./*
  lint:
    <<: *exector
    steps:
      - attach_workspace:
          at: .
      - run: ls -l
      - run:
          name: Run Eslint
          command: npm run lint:js
  deploy:
    <<: *exector
    steps:
      - attach_workspace:
          at: .
      - run: npm install --save firebase-tools
      - run: npm run deploy
workflows:
  version: 2
  deploy_to_hosting:
    jobs:
      - setup
      - lint
