version: 2.1
executors:
  default:
    working_directory: ~/work
    docker:
      - image: circleci/node:10.15
commands:
  restore_npm:
    steps:
      - restore_cache:
          name: Restore npm dependencies
          key: npm-{{ checksum "package-lock.json" }}-{{ .Environment.CACHE_VERSION_NPM }}
  save_npm:
    steps:
      - save_cache:
          name: Cache npm dependencies
          key: npm-{{ checksum "package-lock.json" }}-{{ .Environment.CACHE_VERSION_NPM }}
          paths:
            - ~/work/node_modules
  persist_ws:
    steps:
      - persist_to_workspace:
          root: .
          paths:
            - .
  attach_ws:
    steps:
      - attach_workspace:
          at: .
jobs:
  setup:
    exector:
      name: default
    steps:
      - checkout
      - restore_npm
      - run:
          name: Install dependencies
          command: npm install
      - save_npm
      - persist_ws
  lint:
    exector:
      name: default
    steps:
      - attach_ws
      - run:
          name: Run eslint
          command: npm run lint:js
  deploy:
    exector:
      name: default
    steps:
      - attach_ws
      - run: npm install --save firebase-tools
      - run: npm run deploy
workflows:
  deploy_to_hosting:
    jobs:
      - setup
      - lint:
        requires:
          - setup
      - deploy:
        requires:
          - lint
        filters:
          branches:
            only: master
